# Metadata for your course

title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: # the name of the repository when it is created for the learner
  repo: # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: createIssue
  title: Welcome
  body: welcome-text.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title: Create a new PR
  description: Add your name to the README.md file in your new PR
  event: pull_request.opened
  actions:
  - type: gate
    left: '%payload.pull_request.title%'
                  # you can execute multiple actions in the `before` block
                  #
  # - type:
  #   option:
  #
  # - type:
  #   option:
